package ui.components
{
	import flash.display.Bitmap;
	import flash.utils.Endian;
	import ui.containers.Container;
	import ui.core.UIManager;
	import ui.events.UIEvent;
	import agl.shader.Shader;
	import com.vsdevelop.air.extension.glfw.Gl;
	import agl.utils.Matrix4;
	import flash.display.BitmapData;
	import flash.display.Loader;
	import flash.net.URLRequest;
	import flash.events.Event;
	import flash.events.IOErrorEvent;
	import flash.geom.Matrix3D;
	import flash.utils.ByteArray;
	import flash.geom.Rectangle;

	/**
	 * 图片组件类
	 * 提供图片显示功能，支持纹理加载、缩放模式和事件处理
	 * 继承自Container，支持布局管理器和约束功能
	 * @author Generated by AI Assistant
	 */
	public class Image extends Container
	{
		// 缩放模式枚举
		public static const SCALE_MODE_STRETCH:String = "stretch";     // 拉伸填充
		public static const SCALE_MODE_FIT:String = "fit";             // 等比缩放适应
		public static const SCALE_MODE_FILL:String = "fill";           // 等比缩放填充
		public static const SCALE_MODE_NONE:String = "none";           // 原始大小
		
		// 图片属性
		private var _source:String = "";
		private var _scaleMode:String = SCALE_MODE_STRETCH;
		private var _smooth:Boolean = true;
		
		
		// 自动尺寸相关属性
		private var _autoSize:Boolean = false;
		private var _minWidth:Number = 16;
		private var _minHeight:Number = 16;
		private var _maxWidth:Number = Number.MAX_VALUE;
		private var _maxHeight:Number = Number.MAX_VALUE;
		private var _preferredWidth:Number = 100;
		private var _preferredHeight:Number = 100;
		
		// 内边距
		private var _paddingLeft:Number = 0;
		private var _paddingRight:Number = 0;
		private var _paddingTop:Number = 0;
		private var _paddingBottom:Number = 0;
		
		// 纹理相关
		private var _texture:uint = 0;
		private var _textureWidth:Number = 0;
		private var _textureHeight:Number = 0;
		private var _isLoaded:Boolean = false;
		
		// 加载相关
		private var _loader:Loader;
		private var _bitmapData:BitmapData;
		
		// 着色器资源
		[Embed(source="../../assets/ui/ui_vertex.glsl", mimeType="application/octet-stream")]
		private var VertexShaderSource:Class;
		
		[Embed(source="../../assets/ui/ui_fragment.glsl", mimeType="application/octet-stream")]
		private var FragmentShaderSource:Class;
		
		// 渲染相关
		private var _modelMatrix:Matrix4;
		private var _textureVertices:Vector.<Number>;
		
		/**
		 * 构造函数
		 * @param x X坐标
		 * @param y Y坐标
		 * @param width 宽度
		 * @param height 高度
		 * @param source 图片源路径
		 */
		public function Image(x:Number = 0, y:Number = 0, width:Number = 100, height:Number = 100, source:String = "")
		{
			super(x, y, width, height);
			_source = source;
			
			initializeImage();
			
			if (_source && _source.length > 0)
			{
				loadImage(_source);
			}
		}
		
		/**
		 * 初始化图片组件
		 */
		private function initializeImage():void
		{
			// 创建着色器
			var vs:String = new VertexShaderSource();
			var fs:String = new FragmentShaderSource();
			_shader = new Shader(vs, fs);
			
			// 创建模型矩阵
			_modelMatrix = new Matrix4();
			
			// 生成纹理对象
			with (Gl)
			{
				_texture = glGenTextures(uint(1));
			}
		}
		
		/**
		 * 加载图片
		 * @param url 图片URL
		 */
		public function loadImage(url:String):void
		{
			_source = url;
			
			// 清理之前的资源
			cleanupPreviousImage();
			
			// 创建新的加载器
			_loader = new Loader();
			_loader.contentLoaderInfo.addEventListener(Event.COMPLETE, onImageLoaded);
			_loader.contentLoaderInfo.addEventListener(IOErrorEvent.IO_ERROR, onImageError);
			_loader.contentLoaderInfo.addEventListener(IOErrorEvent.VERIFY_ERROR, onVerifyError);
			
			try
			{
				_loader.load(new URLRequest(url));
			}
			catch (error:Error)
			{
				trace("Error loading image: " + error.message);
				dispatchEvent(new UIEvent(UIEvent.ERROR, false, false, NaN, NaN, error.message));
			}
		}
		
		/**
		 * 清理之前的图片资源
		 */
		private function cleanupPreviousImage():void
		{
			_isLoaded = false;
			_textureVertices = null;
			
			// 清理之前的加载器
			if (_loader)
			{
				_loader.contentLoaderInfo.removeEventListener(Event.COMPLETE, onImageLoaded);
				_loader.contentLoaderInfo.removeEventListener(IOErrorEvent.IO_ERROR, onImageError);
				_loader.contentLoaderInfo.removeEventListener(IOErrorEvent.VERIFY_ERROR, onVerifyError);
				_loader = null;
			}
			
			// 清理之前的位图数据
			if (_bitmapData)
			{
				_bitmapData.dispose();
				_bitmapData = null;
			}
			
			// 清理OpenGL纹理
			if (_texture > 0)
			{
				Gl.glDeleteTextures(1, _texture);
				// 重新生成纹理对象
				_texture = Gl.glGenTextures(1);
			}
		}
		
		/**
		 * 刷新当前图片
		 * 重新加载当前source指定的图片
		 */
		public function refresh():void
		{
			if (_source && _source.length > 0 && _source != "[Generated]")
			{
				var currentSource:String = _source;
				cleanupPreviousImage();
				loadImage(currentSource);
			}
		}
		
		private function onVerifyError(e:IOErrorEvent):void 
		{
			trace(e);
		}
		
		/**
		 * 从BitmapData直接加载图片
		 * @param bitmapData 位图数据
		 */
		public function loadFromBitmapData(bitmapData:BitmapData):void
		{
			if (!bitmapData)
			{
				trace("Error: BitmapData is null");
				dispatchEvent(new UIEvent(UIEvent.ERROR, false, false, NaN, NaN, "BitmapData is null"));
				return;
			}
			
			try
			{
				// 清理之前的资源
				cleanupPreviousImage();
				
				// 设置新的位图数据
				_bitmapData = bitmapData.clone();
				_textureWidth = _bitmapData.width;
				_textureHeight = _bitmapData.height;
				_source = "[Generated]";
				
				// 创建OpenGL纹理
				createTexture();
				
				// 更新顶点数据
				updateTextureVertices();
				_isLoaded = true;
				
				// 如果启用了自动尺寸，更新组件尺寸
				if (_autoSize)
				{
					updateAutoSize();
				}
				
				_needsRedraw = true;
				
				// 派发加载完成事件
				dispatchEvent(new UIEvent(UIEvent.COMPLETE));
			}
			catch (error:Error)
			{
				trace("Error loading from BitmapData: " + error.message);
				dispatchEvent(new UIEvent(UIEvent.ERROR, false, false, NaN, NaN, error.message));
			}
		}
		
		/**
		 * 图片加载完成事件处理
		 * @param event 事件对象
		 */
		private function onImageLoaded(event:Event):void
		{
			try
			{
				// 获取位图数据
				loadFromBitmapData((_loader.content as Bitmap).bitmapData);
			}
			catch (error:Error)
			{
				trace("Error processing loaded image: " + error.message);
				dispatchEvent(new UIEvent(UIEvent.ERROR, false, false, NaN, NaN, error.message));
			}
		}
		
		/**
		 * 图片加载错误事件处理
		 * @param event 事件对象
		 */
		private function onImageError(event:IOErrorEvent):void
		{
			trace("Error loading image: " + event.text);
			dispatchEvent(new UIEvent(UIEvent.ERROR, false, false, NaN, NaN, String(event.text)));
		}
		
		/**
		 * 创建OpenGL纹理
		 */
		private function createTexture():void
		{
			if (!_bitmapData) return;
			
			with (Gl)
			{
				// 绑定纹理
				glBindTexture(GL_TEXTURE_2D, _texture);
				
				// 设置纹理参数
				if (_smooth)
				{
					glTexParameteri(GL_TEXTURE_2D, uint(GL_TEXTURE_MIN_FILTER), uint(GL_LINEAR));
					glTexParameteri(GL_TEXTURE_2D, uint(GL_TEXTURE_MAG_FILTER), uint(GL_LINEAR));
				}
				else
				{
					glTexParameteri(GL_TEXTURE_2D, uint(GL_TEXTURE_MIN_FILTER), uint(GL_NEAREST));
					glTexParameteri(GL_TEXTURE_2D, uint(GL_TEXTURE_MAG_FILTER), uint(GL_NEAREST));
				}
				
				glTexParameteri(GL_TEXTURE_2D, uint(GL_TEXTURE_WRAP_S), uint(GL_CLAMP_TO_EDGE));
				glTexParameteri(GL_TEXTURE_2D, uint(GL_TEXTURE_WRAP_T), uint(GL_CLAMP_TO_EDGE));
			
			
			
			
			// 上传纹理数据
			var pixelBytes:ByteArray = new ByteArray();
			pixelBytes.endian = Endian.LITTLE_ENDIAN;
			
			_bitmapData.copyPixelsToByteArray(_bitmapData.rect, pixelBytes);
			
			
			//var pixels:Vector.<uint> = _bitmapData.getVector(_bitmapData.rect);
			//for (var i:int = 0; i < pixels.length; i++)
			//{
				//var pixel:uint = pixels[i];
				//pixelBytes.writeByte((pixel >> 16) & 0xFF); // R
				//pixelBytes.writeByte((pixel >> 8) & 0xFF);  // G
				//pixelBytes.writeByte(pixel & 0xFF);         // B
				//pixelBytes.writeByte((pixel >> 24) & 0xFF); // A
			//}
				
				pixelBytes.position = 0;
				
				glTexImage2D(GL_TEXTURE_2D, uint(0), GL_RGBA, uint(_textureWidth), uint(_textureHeight),uint(0), GL_BGRA, GL_UNSIGNED_BYTE, pixelBytes);
				//glTexImage2D(GL_TEXTURE_2D, uint(0), GL_BGRA, uint(_textureWidth), uint(_textureHeight),uint(0), GL_BGRA, GL_UNSIGNED_BYTE, pixelBytes);
				
				// 解绑纹理
				glBindTexture(GL_TEXTURE_2D, 0);
			}
		}
		
		/**
		 * 更新纹理顶点数据
		 */
		private function updateTextureVertices():void
		{
			if (!_isLoaded) return;
			
			var renderX:Number = _x;
			var renderY:Number = _y;
			var renderWidth:Number = _width;
			var renderHeight:Number = _height;
			
			// 纹理坐标（默认为完整纹理）
			var texLeft:Number = 0.0;
			var texRight:Number = 1.0;
			var texTop:Number = 1.0;
			var texBottom:Number = 0.0;
			
			// 根据缩放模式计算渲染尺寸和位置
			switch (_scaleMode)
			{
				case SCALE_MODE_FIT:
					// 等比缩放适应：保持宽高比，完全显示在容器内
					var scaleX:Number = _width / _textureWidth;
					var scaleY:Number = _height / _textureHeight;
					var scale:Number = Math.min(scaleX, scaleY);
					renderWidth = _textureWidth * scale;
					renderHeight = _textureHeight * scale;
					renderX = _x + (_width - renderWidth) * 0.5;
					renderY = _y + (_height - renderHeight) * 0.5;
					break;
					
				case SCALE_MODE_FILL:
					// 等比缩放填充：保持宽高比，填满容器（可能裁剪）
					scaleX = _width / _textureWidth;
					scaleY = _height / _textureHeight;
					scale = Math.max(scaleX, scaleY);
					
					// 计算实际渲染尺寸
					var actualWidth:Number = _textureWidth * scale;
					var actualHeight:Number = _textureHeight * scale;
					
					// 保持渲染区域为组件大小
					renderWidth = _width;
					renderHeight = _height;
					
					// 调整纹理坐标以实现裁剪效果
					var texScaleX:Number = _width / actualWidth;
					var texScaleY:Number = _height / actualHeight;
					
					texLeft = (1.0 - texScaleX) * 0.5;
					texRight = texLeft + texScaleX;
					texTop = 1.0 - (1.0 - texScaleY) * 0.5;
					texBottom = texTop - texScaleY;
					break;
					
				case SCALE_MODE_NONE:
					// 原始大小：居中显示
					renderWidth = _textureWidth;
					renderHeight = _textureHeight;
					renderX = _x + (_width - renderWidth) * 0.5;
					renderY = _y + (_height - renderHeight) * 0.5;
					break;
					
				default: // SCALE_MODE_STRETCH
					// 拉伸填充：直接使用组件尺寸
					break;
			}
			
			// 创建顶点数据（位置x,y,z + 纹理坐标u,v）
			_textureVertices = new <Number>[
				// 第一个三角形
				renderX, renderY, 0, texLeft, texTop,                           // 左上
				renderX + renderWidth, renderY, 0, texRight, texTop,            // 右上
				renderX, renderY + renderHeight, 0, texLeft, texBottom,        // 左下
				
				// 第二个三角形
				renderX + renderWidth, renderY, 0, texRight, texTop,            // 右上
				renderX + renderWidth, renderY + renderHeight, 0, texRight, texBottom, // 右下
				renderX, renderY + renderHeight, 0, texLeft, texBottom         // 左下
			];
			
			// 直接更新VBO，避免调用updateVertexData造成死循环
			super.updateVertexData(_textureVertices);
		}
		
		
		/**
		 * 重写基类的位置和尺寸设置器，确保图片重新计算顶点
		 */
		public override function set x(value:Number):void
		{
			if (_x != value)
			{
				_x = value;
				_bounds.x = value;
				if (_isLoaded)
				{
					updateTextureVertices();
				}
				_needsRedraw = true;
			}
		}
		
		public override function set y(value:Number):void
		{
			if (_y != value)
			{
				_y = value;
				_bounds.y = value;
				if (_isLoaded)
				{
					updateTextureVertices();
				}
				_needsRedraw = true;
			}
		}
		
		public override function set width(value:Number):void
		{
			if (_width != value)
			{
				_width = value;
				_bounds.width = value;
				if (_isLoaded)
				{
					updateTextureVertices();
				}
				_needsRedraw = true;
			}
		}
		
		public override function set height(value:Number):void
		{
			if (_height != value)
			{
				_height = value;
				_bounds.height = value;
				if (_isLoaded)
				{
					updateTextureVertices();
				}
				_needsRedraw = true;
			}
		}
		
		/**
		 * 重写渲染方法
		 */
		protected override function doRender():void
		{
			if (!_shader || !_isLoaded) return;
			
			// 使用着色器程序
			_shader.useProgram();
			
			// 设置模型矩阵
			_modelMatrix.identity();
			_shader.setMatrix4fv("uModel", _modelMatrix);
			
			// 设置投影矩阵
			var uiManager:UIManager = UIManager.getInstance();
			_shader.setMatrix4fv("uProjection", uiManager.projectionMatrix);
			
			// 设置着色器参数和绘制图片
			with (Gl)
			{
				// 设置颜色（白色，不影响纹理）
				glUniform4f(glGetUniformLocation(_shader.program, "uColor"), 1.0, 1.0, 1.0, 1.0);
				
				// 设置透明度
				glUniform1f(glGetUniformLocation(_shader.program, "uAlpha"), _alpha);
				
				// 设置使用纹理
				glUniform1i(glGetUniformLocation(_shader.program, "uUseTexture"), 1);
				
				// 绑定纹理
				glActiveTexture(GL_TEXTURE0);
				glBindTexture(GL_TEXTURE_2D, uint(_texture));
				glUniform1i(glGetUniformLocation(_shader.program, "uTexture"), 0);
				
				// 绘制图片
				glBindVertexArray(uint(_VAO));
				glDrawArrays(GL_TRIANGLES, uint(0), uint(6));
				glBindVertexArray(uint(0));
				
				// 解绑纹理
				glBindTexture(GL_TEXTURE_2D, uint(0));
			}
		}
		
		/**
		 * 重写dispose方法
		 */
		public override function dispose():void
		{
			// 清理加载器
			if (_loader)
			{
				_loader.contentLoaderInfo.removeEventListener(Event.COMPLETE, onImageLoaded);
				_loader.contentLoaderInfo.removeEventListener(IOErrorEvent.IO_ERROR, onImageError);
				_loader.contentLoaderInfo.removeEventListener(IOErrorEvent.VERIFY_ERROR, onVerifyError);
				_loader = null;
			}
			
			// 清理位图数据
			if (_bitmapData)
			{
				_bitmapData.dispose();
				_bitmapData = null;
			}
			
			// 删除纹理
			if (_texture > 0)
			{
				Gl.glDeleteTextures(uint(1), _texture);
				_texture = 0;
			}
			
			super.dispose();
		}
		
		// 属性访问器
		public function get source():String { return _source; }
		public function set source(value:String):void
		{
			if (_source != value)
			{
				if (value && value.length > 0)
				{
					// 加载新图片
					loadImage(value);
					
					// 如果启用了自动尺寸，在图片加载完成后更新尺寸
					if (_autoSize && _isLoaded)
					{
						updateAutoSize();
					}
				}
				else
				{
					// 清空图片
					cleanupPreviousImage();
					_source = value || "";
					_needsRedraw = true;
				}
			}
		}
		
		public function get scaleMode():String { return _scaleMode; }
		public function set scaleMode(value:String):void
		{
			if (_scaleMode != value)
			{
				_scaleMode = value;
				updateTextureVertices();
				_needsRedraw = true;
			}
		}
		
		public function get smooth():Boolean { return _smooth; }
		public function set smooth(value:Boolean):void
		{
			if (_smooth != value)
			{
				_smooth = value;
				if (_isLoaded)
				{
					createTexture(); // 重新创建纹理以应用新的过滤设置
					_needsRedraw = true;
				}
			}
		}
		
		public function get isLoaded():Boolean { return _isLoaded; }
		public function get textureWidth():Number { return _textureWidth; }
		public function get textureHeight():Number { return _textureHeight; }
		
		// ========== 布局约束增强功能 ==========
		
		/**
		 * 获取组件的首选尺寸
		 * 根据图片原始尺寸和内边距自动计算
		 * @return 首选尺寸矩形
		 */
		public override function getPreferredSize():Rectangle
		{
			if (_autoSize && _isLoaded)
			{
				// 计算包含内边距的首选尺寸
				var prefWidth:Number = _textureWidth + _paddingLeft + _paddingRight;
				var prefHeight:Number = _textureHeight + _paddingTop + _paddingBottom;
				
				// 应用最小和最大尺寸限制
				prefWidth = Math.max(_minWidth, Math.min(_maxWidth, prefWidth));
				prefHeight = Math.max(_minHeight, Math.min(_maxHeight, prefHeight));
				
				return new Rectangle(0, 0, prefWidth, prefHeight);
			}
			
			// 如果不是自动尺寸，返回预设的首选尺寸
			return new Rectangle(0, 0, _preferredWidth, _preferredHeight);
		}
		
		/**
		 * 设置布局约束
		 * @param constraints 约束对象，可包含各种布局参数
		 */
		public function setLayoutConstraints(constraints:Object):void
		{
			if (!constraints) return;
			
			// BorderLayout约束
			if (constraints.hasOwnProperty("borderRegion"))
			{
				borderRegion = constraints.borderRegion;
			}
			
			// LinearLayout约束
			if (constraints.hasOwnProperty("layoutWeight"))
			{
				layoutWeight = constraints.layoutWeight;
			}
			
			// GridLayout约束
			if (constraints.hasOwnProperty("gridPosition"))
			{
				gridPosition = constraints.gridPosition;
			}
			else if (constraints.hasOwnProperty("row") || constraints.hasOwnProperty("col"))
			{
				// 支持直接设置行列
				gridPosition = {
					row: constraints.row || 0,
					col: constraints.col || 0,
					rowSpan: constraints.rowSpan || 1,
					colSpan: constraints.colSpan || 1
				};
			}
			
			// 尺寸约束
			if (constraints.hasOwnProperty("preferredWidth"))
			{
				_preferredWidth = constraints.preferredWidth;
			}
			if (constraints.hasOwnProperty("preferredHeight"))
			{
				_preferredHeight = constraints.preferredHeight;
			}
			if (constraints.hasOwnProperty("minWidth"))
			{
				_minWidth = constraints.minWidth;
			}
			if (constraints.hasOwnProperty("minHeight"))
			{
				_minHeight = constraints.minHeight;
			}
			if (constraints.hasOwnProperty("maxWidth"))
			{
				_maxWidth = constraints.maxWidth;
			}
			if (constraints.hasOwnProperty("maxHeight"))
			{
				_maxHeight = constraints.maxHeight;
			}
		}
		
		// ========== 自动尺寸相关属性访问器 ==========
		
		/**
		 * 设置是否启用自动尺寸
		 * @param value 是否启用自动尺寸
		 */
		public function set autoSize(value:Boolean):void
		{
			_autoSize = value;
			if (_autoSize && _isLoaded)
			{
				// 启用自动尺寸时，立即重新计算尺寸
				updateAutoSize();
			}
		}
		
		/**
		 * 获取是否启用自动尺寸
		 * @return 是否启用自动尺寸
		 */
		public function get autoSize():Boolean
		{
			return _autoSize;
		}
		
		/**
		 * 更新自动尺寸
		 */
		private function updateAutoSize():void
		{
			if (_autoSize && _isLoaded)
			{
				var preferredSize:Rectangle = getPreferredSize();
				width = preferredSize.width;
				height = preferredSize.height;
			}
		}
		
		/**
		 * 设置内边距
		 * @param left 左内边距
		 * @param top 上内边距
		 * @param right 右内边距
		 * @param bottom 下内边距
		 */
		public function setPadding(left:Number, top:Number, right:Number, bottom:Number):void
		{
			_paddingLeft = left;
			_paddingTop = top;
			_paddingRight = right;
			_paddingBottom = bottom;
			
			// 如果启用自动尺寸，重新计算
			if (_autoSize)
			{
				updateAutoSize();
			}
		}
		
		/**
		 * 获取内边距
		 * @return 内边距对象 {left, top, right, bottom}
		 */
		public function getPadding():Object
		{
			return {
				left: _paddingLeft,
				top: _paddingTop,
				right: _paddingRight,
				bottom: _paddingBottom
			};
		}
	}
}