package ui.core
{
	import flash.events.EventDispatcher;
	import flash.geom.Rectangle;
	import com.vsdevelop.air.extension.glfw.Gl;
	import agl.shader.Shader;

	/**
	 * UI组件基类
	 * 提供所有UI组件的基础功能，包括位置、大小、可见性、事件处理等
	 * @author Generated by AI Assistant
	 */
	public class UIComponent extends EventDispatcher
	{
		// 基础属性
		protected var _x:Number = 0;
		protected var _y:Number = 0;
		protected var _width:Number = 100;
		protected var _height:Number = 100;
		protected var _visible:Boolean = true;
		protected var _enabled:Boolean = true;
		protected var _alpha:Number = 1.0;
		
		// 渲染相关
		protected var _needsRedraw:Boolean = true;
		protected var _bounds:Rectangle;
		protected var _shader:Shader;
		
		// OpenGL资源
		protected var _VAO:int = 0;
		protected var _VBO:int = 0;
		protected var _vertices:Vector.<Number>;
		
		// 子组件管理
		protected var _children:Vector.<UIComponent>;
		protected var _parent:UIComponent;
		
		/**
		 * 构造函数
		 * @param x X坐标
		 * @param y Y坐标
		 * @param width 宽度
		 * @param height 高度
		 */
		public function UIComponent(x:Number = 0, y:Number = 0, width:Number = 100, height:Number = 100)
		{
			super();
			_x = x;
			_y = y;
			_width = width;
			_height = height;
			_bounds = new Rectangle(x, y, width, height);
			_children = new Vector.<UIComponent>();
			_parent = null;
			
			initializeGL();
		}
		
		/**
		 * 初始化OpenGL资源
		 */
		protected function initializeGL():void
		{
			// 创建顶点数组对象和缓冲区
			with (Gl)
			{
				_VAO = glGenVertexArrays(uint(1));
				_VBO = glGenBuffers(uint(1));
			}
			
			// 生成默认的矩形顶点数据
			updateVertices();
		}
		
		/**
		 * 获取组件的绝对坐标（包括所有父容器的偏移）
		 * @return 包含绝对x和y坐标的对象
		 */
		protected function getAbsolutePosition():Object
		{
			var absX:Number = _x;
			var absY:Number = _y;
			
			// 累加所有父容器的坐标偏移
			var currentParent:UIComponent = _parent;
			while (currentParent != null)
			{
				absX += currentParent._x;
				absY += currentParent._y;
				currentParent = currentParent._parent;
			}
			
			return {x: absX, y: absY};
		}
		
		/**
		 * 更新顶点数据
		 */
		protected function updateVertices():void
		{
			// 获取绝对坐标
			var absPos:Object = getAbsolutePosition();
			var absX:Number = absPos.x;
			var absY:Number = absPos.y;
			
			// 创建矩形顶点数据 (位置 + 纹理坐标)
			_vertices = new <Number>[
				// 位置 (x, y, z)     纹理坐标 (u, v)
				absX, absY, 0,         0, 0,
				absX + _width, absY, 0, 1.0, 0,
				absX + _width, absY + _height, 0, 1, 1,
				
				absX, absY, 0,         0, 0,
				absX + _width, absY + _height, 0, 1, 1,
				absX, absY + _height, 0, 0, 1
			];
			
			updateVertexData(_vertices);
		}
		
		/**
		 * 更新顶点数据到OpenGL缓冲区
		 * @param vertices 顶点数据，如果为null则使用当前的_vertices
		 */
		protected function updateVertexData(vertices:Vector.<Number> = null):void
		{
			if (vertices != null)
			{
				_vertices = vertices;
			}
			
			if (_vertices == null) return;
			
			// 更新OpenGL缓冲区
			with (Gl)
			{
				glBindVertexArray(uint(_VAO));
				glBindBuffer(GL_ARRAY_BUFFER, uint(_VBO));
				glBufferData(GL_ARRAY_BUFFER, uint(4 * _vertices.length), _vertices, GL_DYNAMIC_DRAW);
				
				// 设置顶点属性指针
				// 位置属性
				glVertexAttribPointer(uint(0), 3, GL_FLOAT, GL_FALSE, uint(5 * 4), uint(0));
				glEnableVertexAttribArray(uint(0));
				
				// 纹理坐标属性
				glVertexAttribPointer(uint(1), 2, GL_FLOAT, GL_FALSE, uint(5 * 4), uint(3 * 4));
				glEnableVertexAttribArray(uint(1));
				
				glBindVertexArray(uint(0));
			}
			_needsRedraw = false;
		}
		
		/**
		 * 渲染组件
		 */
		public function render():void
		{
			if (!_visible || _alpha <= 0) return;
			
			if (_needsRedraw)
			{
				updateVertices();
			}
			
			// 子类实现具体的渲染逻辑
			doRender();
		}
		
		/**
		 * 子类重写此方法实现具体的渲染逻辑
		 */
		protected function doRender():void
		{
			// 默认实现：绘制一个简单的矩形
			if (_shader)
			{
				_shader.useProgram();
				with (Gl)
				{
					glBindVertexArray(uint(_VAO));
					glDrawArrays(GL_TRIANGLES, uint(0), uint(6));
					glBindVertexArray(uint(0));
				}
			}
		}
		
		/**
		 * 检查点是否在组件内
		 * @param pointX X坐标（绝对坐标）
		 * @param pointY Y坐标（绝对坐标）
		 * @return 是否在组件内
		 */
		public function hitTest(pointX:Number, pointY:Number):Boolean
		{
			if (!_visible || !_enabled) return false;
			
			// 获取组件的绝对坐标
			var absPos:Object = getAbsolutePosition();
			var absX:Number = absPos.x;
			var absY:Number = absPos.y;
			
			// 使用绝对坐标进行点击测试
			return pointX >= absX && pointX <= absX + _width &&
				   pointY >= absY && pointY <= absY + _height;
		}
		
		/**
		 * 递归更新所有子组件的顶点数据
		 */
		protected function updateChildrenVertices():void
		{
			for (var i:int = 0; i < _children.length; i++)
			{
				var child:UIComponent = _children[i];
				child.updateVertices();
				child.updateChildrenVertices(); // 递归更新子组件的子组件
			}
		}
		
		/**
		 * 添加子组件
		 * @param child 要添加的子组件
		 * @return 添加的子组件
		 */
		public function addChild(child:UIComponent):UIComponent
		{
			if (child == null || child == this)
				return child;
				
			// 如果子组件已经有父组件，先从原父组件中移除
			if (child._parent != null)
			{
				child._parent.removeChild(child);
			}
			
			// 添加到子组件列表
			_children.push(child);
			child._parent = this;
			
			// 更新子组件的顶点数据（因为父组件改变了）
			child.updateVertices();
			child.updateChildrenVertices();
			
			return child;
		}
		
		/**
		 * 移除子组件
		 * @param child 要移除的子组件
		 * @return 移除的子组件
		 */
		public function removeChild(child:UIComponent):UIComponent
		{
			if (child == null)
				return null;
				
			var index:int = _children.indexOf(child);
			if (index >= 0)
			{
				return removeChildAt(index);
			}
			
			return null;
		}
		
		/**
		 * 根据索引移除子组件
		 * @param index 子组件索引
		 * @return 移除的子组件
		 */
		public function removeChildAt(index:int):UIComponent
		{
			if (index < 0 || index >= _children.length)
				return null;
				
			var child:UIComponent = _children[index];
			_children.splice(index, 1);
			child._parent = null;
			
			return child;
		}
		
		/**
		 * 获取子组件列表的副本
		 * @return 子组件列表
		 */
		public function getChildren():Vector.<UIComponent>
		{
			return _children.slice();
		}
		
		/**
		 * 获取子组件数量
		 * @return 子组件数量
		 */
		public function get numChildren():int
		{
			return _children.length;
		}
		
		/**
		 * 根据索引获取子组件
		 * @param index 子组件索引
		 * @return 子组件
		 */
		public function getChildAt(index:int):UIComponent
		{
			if (index < 0 || index >= _children.length)
				return null;
				
			return _children[index];
		}
		
		/**
		 * 获取父组件
		 * @return 父组件
		 */
		public function get parent():UIComponent
		{
			return _parent;
		}
		
		/**
		 * 释放OpenGL资源
		 */
		public function dispose():void
		{
			// 释放所有子组件
			for (var i:int = 0; i < _children.length; i++)
			{
				_children[i].dispose();
			}
			_children.length = 0;
			
			// 从父组件中移除
			if (_parent != null)
			{
				_parent.removeChild(this);
			}
			
			if (_VAO > 0)
			{
				var arrays:Vector.<uint> = new Vector.<uint>(1);
				arrays[0] = _VAO;
				Gl.glDeleteVertexArrays(uint(1), arrays);
				_VAO = 0;
			}
			
			if (_VBO > 0)
			{
				Gl.glDeleteBuffers(uint(1), _VBO);
				_VBO = 0;
			}
		}
		
		// 属性访问器
		public function get x():Number { return _x; }
		public function set x(value:Number):void
		{
			if (_x != value)
			{
				_x = value;
				_bounds.x = value;
				_needsRedraw = true;
				updateVertices(); // 更新顶点数据以反映位置变化
				updateChildrenVertices(); // 更新所有子组件的顶点数据
			}
		}
		
		public function get y():Number { return _y; }
		public function set y(value:Number):void
		{
			if (_y != value)
			{
				_y = value;
				_bounds.y = value;
				_needsRedraw = true;
				updateVertices(); // 更新顶点数据以反映位置变化
				updateChildrenVertices(); // 更新所有子组件的顶点数据
			}
		}
		
		public function get width():Number { return _width; }
		public function set width(value:Number):void
		{
			if (_width != value)
			{
				_width = value;
				_bounds.width = value;
				_needsRedraw = true;
				updateVertices(); // 更新顶点数据以反映尺寸变化
			}
		}
		
		public function get height():Number { return _height; }
		public function set height(value:Number):void
		{
			if (_height != value)
			{
				_height = value;
				_bounds.height = value;
				_needsRedraw = true;
				updateVertices(); // 更新顶点数据以反映尺寸变化
			}
		}
		
		public function get visible():Boolean { return _visible; }
		public function set visible(value:Boolean):void { _visible = value; }
		
		public function get enabled():Boolean { return _enabled; }
		public function set enabled(value:Boolean):void { _enabled = value; }
		
		public function get alpha():Number { return _alpha; }
		public function set alpha(value:Number):void { _alpha = Math.max(0, Math.min(1, value)); }
		
		public function get bounds():Rectangle { return _bounds.clone(); }
		
		/**
		 * 设置着色器
		 * @param shader 着色器对象
		 */
		public function setShader(shader:Shader):void
		{
			_shader = shader;
		}
	}
}