package ui.test
{
	import ui.test.UITestCase;
	import ui.containers.Container;
	import ui.core.UIComponent;
	import ui.layout.LinearLayout;
	import ui.layout.GridLayout;
	import ui.layout.BorderLayout;
	import flash.geom.Rectangle;

	/**
	 * 布局管理器测试用例
	 * 测试LinearLayout、GridLayout、BorderLayout的功能
	 * @author Generated by AI Assistant
	 */
	public class LayoutTestCase extends UITestCase
	{
		private var _testContainer:Container;
		private var _testComponents:Vector.<UIComponent>;
		
		/**
		 * 构造函数
		 */
		public function LayoutTestCase()
		{
			super();
		}
		
		/**
		 * 设置测试环境
		 */
		protected function setUp():void
		{
			
			// 创建测试容器
			_testContainer = new Container(50, 50, 400, 300);
			_testComponents = new Vector.<UIComponent>();
			
			// 创建测试组件
			createTestComponents();
		}
		
		/**
		 * 创建测试组件
		 */
		private function createTestComponents():void
		{
			// 创建5个测试组件
			for (var i:int = 0; i < 5; i++)
			{
				var component:UIComponent = new UIComponent(0, 0, 60, 40);
				_testComponents.push(component);
			}
		}
		
		/**
		 * 清理测试环境
		 */
		protected function tearDown():void
		{
			if (_testContainer)
			{
				_testContainer.dispose();
				_testContainer = null;
			}
			
			if (_testComponents)
			{
				for (var i:int = 0; i < _testComponents.length; i++)
				{
					_testComponents[i].dispose();
				}
				_testComponents.length = 0;
				_testComponents = null;
			}
		}
		
		/**
		 * 运行所有布局测试
		 */
		public function runTests():void
		{
			trace("[LayoutTestCase] 开始布局管理器测试...");
			
			try
			{
				// LinearLayout 测试
				testLinearLayoutHorizontal();
				testLinearLayoutVertical();
				testLinearLayoutWithWeight();
				testLinearLayoutAlignment();
				
				// GridLayout 测试
				testGridLayoutBasic();
				testGridLayoutSpanning();
				testGridLayoutAlignment();
				testGridLayoutDynamicSize();
				
				// BorderLayout 测试
				testBorderLayoutBasic();
				testBorderLayoutRegions();
				testBorderLayoutSizing();
				
				trace("[LayoutTestCase] 所有布局测试通过!");
				dispatchTestComplete();
			}
			catch (error:Error)
			{
				trace("[LayoutTestCase] 测试失败: " + error.message);
				dispatchTestFailed(error.message);
			}
		}
		
		// ========== LinearLayout 测试 ==========
		
		/**
		 * 测试水平线性布局
		 */
		private function testLinearLayoutHorizontal():void
		{
			trace("[LayoutTestCase] 测试水平线性布局...");
			
			// 清空容器
			clearContainer();
			
			// 设置水平线性布局
			var layout:LinearLayout = new LinearLayout(LinearLayout.HORIZONTAL);
			layout.setSpacing(10);
			layout.setPadding(5, 5, 5, 5);
			_testContainer.setLayoutManager(layout);
			
			// 添加测试组件
			for (var i:int = 0; i < 3; i++)
			{
				_testContainer.addChild(_testComponents[i]);
			}
			
			// 验证布局结果
			var expectedX:Number = 5; // 左内边距
			for (i = 0; i < 3; i++)
			{
				var component:UIComponent = _testComponents[i];
				assertEquals("水平布局X坐标", expectedX, component.x);
				assertEquals("水平布局Y坐标", 5, component.y); // 上内边距
				
				expectedX += component.width + (i < 2 ? 10 : 0); // 宽度 + 间距
			}
			
			trace("[LayoutTestCase] 水平线性布局测试通过");
		}
		
		/**
		 * 测试垂直线性布局
		 */
		private function testLinearLayoutVertical():void
		{
			trace("[LayoutTestCase] 测试垂直线性布局...");
			
			// 清空容器
			clearContainer();
			
			// 设置垂直线性布局
			var layout:LinearLayout = new LinearLayout(LinearLayout.VERTICAL);
			layout.setSpacing(8);
			layout.setPadding(10, 10, 10, 10);
			_testContainer.setLayoutManager(layout);
			
			// 添加测试组件
			for (var i:int = 0; i < 3; i++)
			{
				_testContainer.addChild(_testComponents[i]);
			}
			
			// 验证布局结果
			var expectedY:Number = 10; // 上内边距
			for (i = 0; i < 3; i++)
			{
				var component:UIComponent = _testComponents[i];
				assertEquals("垂直布局X坐标", 10, component.x); // 左内边距
				assertEquals("垂直布局Y坐标", expectedY, component.y);
				
				expectedY += component.height + (i < 2 ? 8 : 0); // 高度 + 间距
			}
			
			trace("[LayoutTestCase] 垂直线性布局测试通过");
		}
		
		/**
		 * 测试带权重的线性布局
		 */
		private function testLinearLayoutWithWeight():void
		{
			trace("[LayoutTestCase] 测试带权重的线性布局...");
			
			// 清空容器
			clearContainer();
			
			// 设置水平线性布局
			var layout:LinearLayout = new LinearLayout(LinearLayout.HORIZONTAL);
			layout.setSpacing(5);
			layout.setPadding(0, 0, 0, 0);
			_testContainer.setLayoutManager(layout);
			
			// 设置组件权重
			_testComponents[0]["layoutWeight"] = 1;
			_testComponents[1]["layoutWeight"] = 2;
			_testComponents[2]["layoutWeight"] = 1;
			
			// 添加测试组件
			for (var i:int = 0; i < 3; i++)
			{
				_testContainer.addChild(_testComponents[i]);
			}
			
			// 验证权重分配（第二个组件应该是其他组件的2倍宽度）
			var comp1Width:Number = _testComponents[0].width;
			var comp2Width:Number = _testComponents[1].width;
			var comp3Width:Number = _testComponents[2].width;
			
			// 权重比例应该是 1:2:1
			assertTrue("权重分配正确", Math.abs(comp2Width - comp1Width * 2) < 5);
			assertTrue("权重分配正确", Math.abs(comp1Width - comp3Width) < 5);
			
			trace("[LayoutTestCase] 带权重的线性布局测试通过");
		}
		
		/**
		 * 测试线性布局对齐
		 */
		private function testLinearLayoutAlignment():void
		{
			trace("[LayoutTestCase] 测试线性布局对齐...");
			
			// 清空容器
			clearContainer();
			
			// 设置水平线性布局，居中对齐
			var layout:LinearLayout = new LinearLayout(LinearLayout.HORIZONTAL);
			layout.setAlignment(LinearLayout.ALIGN_CENTER);
			layout.setPadding(0, 0, 0, 0);
			_testContainer.setLayoutManager(layout);
			
			// 添加一个测试组件
			_testContainer.addChild(_testComponents[0]);
			
			// 验证居中对齐
			var expectedY:Number = (_testContainer.height - _testComponents[0].height) / 2;
			assertTrue("居中对齐", Math.abs(_testComponents[0].y - expectedY) < 5);
			
			trace("[LayoutTestCase] 线性布局对齐测试通过");
		}
		
		// ========== GridLayout 测试 ==========
		
		/**
		 * 测试基本网格布局
		 */
		private function testGridLayoutBasic():void
		{
			trace("[LayoutTestCase] 测试基本网格布局...");
			
			// 清空容器
			clearContainer();
			
			// 设置2x2网格布局
			var layout:GridLayout = new GridLayout(2, 2);
			layout.setSpacing(5);
			layout.setPadding(10, 10, 10, 10);
			_testContainer.setLayoutManager(layout);
			
			// 添加4个测试组件
			for (var i:int = 0; i < 4; i++)
			{
				_testContainer.addChild(_testComponents[i]);
			}
			
			// 验证网格位置
			// 第一行
			assertEquals("网格(0,0)X坐标", 10, _testComponents[0].x);
			assertEquals("网格(0,0)Y坐标", 10, _testComponents[0].y);
			
			// 第二个组件应该在第一行第二列
			var expectedX:Number = 10 + _testComponents[0].width + 5; // 左边距 + 第一个组件宽度 + 间距
			assertEquals("网格(0,1)X坐标", expectedX, _testComponents[1].x);
			assertEquals("网格(0,1)Y坐标", 10, _testComponents[1].y);
			
			trace("[LayoutTestCase] 基本网格布局测试通过");
		}
		
		/**
		 * 测试网格跨行跨列
		 */
		private function testGridLayoutSpanning():void
		{
			trace("[LayoutTestCase] 测试网格跨行跨列...");
			
			// 清空容器
			clearContainer();
			
			// 设置3x3网格布局
			var layout:GridLayout = new GridLayout(3, 3);
			layout.setPadding(0, 0, 0, 0);
			_testContainer.setLayoutManager(layout);
			
			// 设置第一个组件跨2行2列
			_testComponents[0]["gridRowSpan"] = 2;
			_testComponents[0]["gridColumnSpan"] = 2;
			
			// 添加测试组件
			_testContainer.addChild(_testComponents[0]);
			_testContainer.addChild(_testComponents[1]);
			
			// 验证跨行跨列组件的尺寸
			var cellWidth:Number = _testContainer.width / 3;
			var cellHeight:Number = _testContainer.height / 3;
			var expectedWidth:Number = cellWidth * 2;
			var expectedHeight:Number = cellHeight * 2;
			
			assertTrue("跨行跨列宽度", Math.abs(_testComponents[0].width - expectedWidth) < 5);
			assertTrue("跨行跨列高度", Math.abs(_testComponents[0].height - expectedHeight) < 5);
			
			trace("[LayoutTestCase] 网格跨行跨列测试通过");
		}
		
		/**
		 * 测试网格对齐
		 */
		private function testGridLayoutAlignment():void
		{
			trace("[LayoutTestCase] 测试网格对齐...");
			
			// 清空容器
			clearContainer();
			
			// 设置2x2网格布局，居中对齐
			var layout:GridLayout = new GridLayout(2, 2);
			layout.setCellAlignment(GridLayout.ALIGN_CENTER);
			layout.setPadding(0, 0, 0, 0);
			_testContainer.setLayoutManager(layout);
			
			// 添加一个小尺寸的测试组件
			_testComponents[0].width = 30;
			_testComponents[0].height = 20;
			_testContainer.addChild(_testComponents[0]);
			
			// 验证居中对齐（组件应该在单元格中心）
			var cellWidth:Number = _testContainer.width / 2;
			var cellHeight:Number = _testContainer.height / 2;
			var expectedX:Number = (cellWidth - _testComponents[0].width) / 2;
			var expectedY:Number = (cellHeight - _testComponents[0].height) / 2;
			
			assertTrue("网格居中对齐X", Math.abs(_testComponents[0].x - expectedX) < 5);
			assertTrue("网格居中对齐Y", Math.abs(_testComponents[0].y - expectedY) < 5);
			
			trace("[LayoutTestCase] 网格对齐测试通过");
		}
		
		/**
		 * 测试动态网格尺寸
		 */
		private function testGridLayoutDynamicSize():void
		{
			trace("[LayoutTestCase] 测试动态网格尺寸...");
			
			// 清空容器
			clearContainer();
			
			// 设置动态网格布局（行列数为-1表示自动计算）
			var layout:GridLayout = new GridLayout(-1, 3); // 3列，行数自动
			layout.setPadding(0, 0, 0, 0);
			_testContainer.setLayoutManager(layout);
			
			// 添加5个测试组件（应该排列为2行3列，最后一行只有2个）
			for (var i:int = 0; i < 5; i++)
			{
				_testContainer.addChild(_testComponents[i]);
			}
			
			// 验证第4个组件（索引3）应该在第二行第一列
			assertEquals("动态网格第二行X坐标", 0, _testComponents[3].x);
			assertTrue("动态网格第二行Y坐标", _testComponents[3].y > _testComponents[0].y);
			
			trace("[LayoutTestCase] 动态网格尺寸测试通过");
		}
		
		// ========== BorderLayout 测试 ==========
		
		/**
		 * 测试基本边界布局
		 */
		private function testBorderLayoutBasic():void
		{
			trace("[LayoutTestCase] 测试基本边界布局...");
			
			// 清空容器
			clearContainer();
			
			// 设置边界布局
			var layout:BorderLayout = new BorderLayout();
			layout.setPadding(5, 5, 5, 5);
			_testContainer.setLayoutManager(layout);
			
			// 添加组件到不同区域
			layout.addComponent(_testComponents[0], BorderLayout.NORTH);
			layout.addComponent(_testComponents[1], BorderLayout.SOUTH);
			layout.addComponent(_testComponents[2], BorderLayout.WEST);
			layout.addComponent(_testComponents[3], BorderLayout.EAST);
			layout.addComponent(_testComponents[4], BorderLayout.CENTER);
			
			// 添加到容器
			for (var i:int = 0; i < 5; i++)
			{
				_testContainer.addChild(_testComponents[i]);
			}
			
			// 验证北区域位置（应该在顶部）
			assertEquals("北区域Y坐标", 5, _testComponents[0].y);
			assertEquals("北区域X坐标", 5, _testComponents[0].x);
			
			// 验证南区域位置（应该在底部）
			var expectedSouthY:Number = _testContainer.height - _testComponents[1].height - 5;
			assertEquals("南区域Y坐标", expectedSouthY, _testComponents[1].y);
			
			trace("[LayoutTestCase] 基本边界布局测试通过");
		}
		
		/**
		 * 测试边界布局区域设置
		 */
		private function testBorderLayoutRegions():void
		{
			trace("[LayoutTestCase] 测试边界布局区域设置...");
			
			// 清空容器
			clearContainer();
			
			// 设置边界布局
			var layout:BorderLayout = new BorderLayout();
			layout.setPadding(0, 0, 0, 0);
			_testContainer.setLayoutManager(layout);
			
			// 只添加中心区域
			layout.addComponent(_testComponents[0], BorderLayout.CENTER);
			_testContainer.addChild(_testComponents[0]);
			
			// 验证中心区域应该填满整个容器
			assertEquals("中心区域X坐标", 0, _testComponents[0].x);
			assertEquals("中心区域Y坐标", 0, _testComponents[0].y);
			assertEquals("中心区域宽度", _testContainer.width, _testComponents[0].width);
			assertEquals("中心区域高度", _testContainer.height, _testComponents[0].height);
			
			trace("[LayoutTestCase] 边界布局区域设置测试通过");
		}
		
		/**
		 * 测试边界布局自动/固定尺寸
		 */
		private function testBorderLayoutSizing():void
		{
			trace("[LayoutTestCase] 测试边界布局自动/固定尺寸...");
			
			// 清空容器
			clearContainer();
			
			// 设置边界布局，固定北区域高度
			var layout:BorderLayout = new BorderLayout();
			layout.setNorthHeight(50); // 固定北区域高度为50
			layout.setPadding(0, 0, 0, 0);
			_testContainer.setLayoutManager(layout);
			
			// 添加北区域和中心区域
			layout.addComponent(_testComponents[0], BorderLayout.NORTH);
			layout.addComponent(_testComponents[1], BorderLayout.CENTER);
			_testContainer.addChild(_testComponents[0]);
			_testContainer.addChild(_testComponents[1]);
			
			// 验证北区域高度被固定为50
			assertEquals("固定北区域高度", 50, _testComponents[0].height);
			
			// 验证中心区域位置和尺寸
			assertEquals("中心区域Y坐标", 50, _testComponents[1].y);
			assertEquals("中心区域高度", _testContainer.height - 50, _testComponents[1].height);
			
			trace("[LayoutTestCase] 边界布局自动/固定尺寸测试通过");
		}
		
		// ========== 辅助方法 ==========
		
		/**
		 * 清空测试容器
		 */
		private function clearContainer():void
		{
			// 移除所有子组件
			while (_testContainer.numChildren > 0)
			{
				_testContainer.removeChildAt(0);
			}
			
			// 清除布局管理器
			_testContainer.setLayoutManager(null);
			
			// 重置测试组件的属性
			for (var i:int = 0; i < _testComponents.length; i++)
			{
				var component:UIComponent = _testComponents[i];
				component.width = 60;
				component.height = 40;
				
				// 清除自定义属性
				if (component.hasOwnProperty("layoutWeight"))
					delete component["layoutWeight"];
				if (component.hasOwnProperty("gridRowSpan"))
					delete component["gridRowSpan"];
				if (component.hasOwnProperty("gridColumnSpan"))
					delete component["gridColumnSpan"];
				if (component.hasOwnProperty("borderRegion"))
					delete component["borderRegion"];
			}
		}
		
		/**
		 * 断言相等
		 * @param message 错误消息
		 * @param expected 期望值
		 * @param actual 实际值
		 */
		private function assertEquals(message:String, expected:Number, actual:Number):void
		{
			if (Math.abs(expected - actual) > 0.1)
			{
				throw new Error(message + ": 期望 " + expected + ", 实际 " + actual);
			}
		}
		
		/**
		 * 断言为真
		 * @param message 错误消息
		 * @param condition 条件
		 */
		private function assertTrue(message:String, condition:Boolean):void
		{
			if (!condition)
			{
				throw new Error(message + ": 条件为假");
			}
		}
		
		/**
		 * 分发测试完成事件
		 */
		private function dispatchTestComplete():void
		{
			// 这里应该分发测试完成事件，具体实现依赖于UITestCase基类
			trace("[LayoutTestCase] 分发测试完成事件");
		}
		
		/**
		 * 分发测试失败事件
		 * @param message 失败消息
		 */
		private function dispatchTestFailed(message:String):void
		{
			// 这里应该分发测试失败事件，具体实现依赖于UITestCase基类
			trace("[LayoutTestCase] 分发测试失败事件: " + message);
		}
	}
}