package ui.utils
{
	import com.vsdevelop.air.extension.glfw.Gl;
	import agl.shader.Shader;
	import agl.utils.Matrix4;
	import ui.core.UIComponent;
	import flash.utils.ByteArray;
	import flash.utils.Endian;

	/**
	 * 批量渲染管理器
	 * 将多个UI组件的渲染操作合并，减少OpenGL状态切换，提高渲染性能
	 * @author Generated by AI Assistant
	 */
	public class BatchRenderer
	{
		// 单例实例
		private static var _instance:BatchRenderer;
		
		// 批量渲染数据
		private var _vertices:Vector.<Number>;
		private var _indices:Vector.<uint>;
		private var _textures:Vector.<uint>;
		private var _colors:Vector.<Number>;
		
		// OpenGL资源
		private var _batchVAO:uint = 0;
		private var _batchVBO:uint = 0;
		private var _batchEBO:uint = 0;
		
		// 批量状态
		private var _currentBatchSize:int = 0;
		private var _maxBatchSize:int = 1000; // 最大批量大小
		private var _currentTexture:uint = 0;
		private var _currentShader:Shader = null;
		
		// 统计信息
		private var _batchCount:int = 0;
		private var _drawCalls:int = 0;
		private var _verticesRendered:int = 0;
		
		// 顶点属性大小 (位置3 + 纹理坐标2 + 颜色4 = 9个float)
		private static const VERTEX_SIZE:int = 9;
		private static const VERTICES_PER_QUAD:int = 4;
		private static const INDICES_PER_QUAD:int = 6;
		
		/**
		 * 构造函数 (私有)
		 */
		public function BatchRenderer()
		{
			if (_instance)
			{
				throw new Error("BatchRenderer is a singleton class. Use getInstance() instead.");
			}
			
			initializeBatchRenderer();
		}
		
		/**
		 * 获取单例实例
		 * @return BatchRenderer实例
		 */
		public static function getInstance():BatchRenderer
		{
			if (!_instance)
			{
				_instance = new BatchRenderer();
			}
			return _instance;
		}
		
		/**
		 * 初始化批量渲染器
		 */
		private function initializeBatchRenderer():void
		{
			// 初始化数据容器
			_vertices = new Vector.<Number>();
			_indices = new Vector.<uint>();
			_textures = new Vector.<uint>();
			_colors = new Vector.<Number>();
			
			// 创建OpenGL资源
			with (Gl)
			{
				// 生成VAO, VBO, EBO
				_batchVAO = glGenVertexArrays(1);
				_batchVBO = glGenBuffers(1);
				_batchEBO = glGenBuffers(1);
				
				// 绑定VAO
				glBindVertexArray(_batchVAO);
				
				// 绑定VBO
				glBindBuffer(GL_ARRAY_BUFFER, _batchVBO);
				
				// 设置顶点属性
				// 位置属性 (location = 0)
				glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, VERTEX_SIZE * 4, 0);
				glEnableVertexAttribArray(0);
				
				// 纹理坐标属性 (location = 1)
				glVertexAttribPointer(1, 2, GL_FLOAT, GL_FALSE, VERTEX_SIZE * 4, 3 * 4);
				glEnableVertexAttribArray(1);
				
				// 颜色属性 (location = 2)
				glVertexAttribPointer(2, 4, GL_FLOAT, GL_FALSE, VERTEX_SIZE * 4, 5 * 4);
				glEnableVertexAttribArray(2);
				
				// 绑定EBO
				glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, _batchEBO);
				
				// 解绑VAO
				glBindVertexArray(0);
			}
		}
		
		/**
		 * 开始批量渲染
		 * @param shader 使用的着色器
		 */
		public function begin(shader:Shader):void
		{
			_currentShader = shader;
			_currentBatchSize = 0;
			_currentTexture = 0;
			
			// 清空数据容器
			_vertices.length = 0;
			_indices.length = 0;
			_textures.length = 0;
			_colors.length = 0;
			
			// 启用着色器
			if (_currentShader)
			{
				_currentShader.useProgram();
			}
		}
		
		/**
		 * 添加四边形到批量渲染
		 * @param x X坐标
		 * @param y Y坐标
		 * @param width 宽度
		 * @param height 高度
		 * @param textureId 纹理ID (0表示无纹理)
		 * @param color 颜色 (RGBA)
		 * @param alpha 透明度
		 */
		public function addQuad(x:Number, y:Number, width:Number, height:Number, 
							   textureId:uint = 0, color:uint = 0xFFFFFF, alpha:Number = 1.0):void
		{
			// 检查是否需要刷新批量
			if (_currentBatchSize >= _maxBatchSize || 
				(textureId != _currentTexture && _currentTexture != 0))
			{
				flush();
			}
			
			// 设置当前纹理
			if (_currentTexture == 0)
			{
				_currentTexture = textureId;
			}
			
			// 提取颜色分量
			var r:Number = ((color >> 16) & 0xFF) / 255.0;
			var g:Number = ((color >> 8) & 0xFF) / 255.0;
			var b:Number = (color & 0xFF) / 255.0;
			
			// 计算顶点索引偏移
			var vertexOffset:uint = _currentBatchSize * VERTICES_PER_QUAD;
			
			// 添加四个顶点 (左下、右下、右上、左上)
			// 顶点1: 左下
			_vertices.push(x, y, 0.0);           // 位置
			_vertices.push(0.0, 1.0);            // 纹理坐标
			_vertices.push(r, g, b, alpha);      // 颜色
			
			// 顶点2: 右下
			_vertices.push(x + width, y, 0.0);   // 位置
			_vertices.push(1.0, 1.0);            // 纹理坐标
			_vertices.push(r, g, b, alpha);      // 颜色
			
			// 顶点3: 右上
			_vertices.push(x + width, y + height, 0.0); // 位置
			_vertices.push(1.0, 0.0);            // 纹理坐标
			_vertices.push(r, g, b, alpha);      // 颜色
			
			// 顶点4: 左上
			_vertices.push(x, y + height, 0.0);  // 位置
			_vertices.push(0.0, 0.0);            // 纹理坐标
			_vertices.push(r, g, b, alpha);      // 颜色
			
			// 添加索引 (两个三角形)
			_indices.push(vertexOffset + 0, vertexOffset + 1, vertexOffset + 2); // 第一个三角形
			_indices.push(vertexOffset + 2, vertexOffset + 3, vertexOffset + 0); // 第二个三角形
			
			_currentBatchSize++;
		}
		
		/**
		 * 刷新当前批量，执行实际渲染
		 */
		public function flush():void
		{
			if (_currentBatchSize == 0 || !_currentShader)
			{
				return;
			}
			
			with (Gl)
			{
				// 绑定VAO
				glBindVertexArray(_batchVAO);
				
				// 上传顶点数据
				glBindBuffer(GL_ARRAY_BUFFER, _batchVBO);
				var vertexData:ByteArray = vectorToByteArray(_vertices);
				glBufferData(GL_ARRAY_BUFFER, vertexData.length, vertexData, GL_DYNAMIC_DRAW);
				
				// 上传索引数据
				glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, _batchEBO);
				var indexData:ByteArray = vectorToByteArrayUint(_indices);
				glBufferData(GL_ELEMENT_ARRAY_BUFFER, indexData.length, indexData, GL_DYNAMIC_DRAW);
				
				// 绑定纹理
				if (_currentTexture > 0)
				{
					glActiveTexture(GL_TEXTURE0);
					glBindTexture(GL_TEXTURE_2D, _currentTexture);
					glUniform1i(glGetUniformLocation(_currentShader.program, "uTexture"), 0);
					glUniform1i(glGetUniformLocation(_currentShader.program, "uUseTexture"), 1);
				}
				else
				{
					glUniform1i(glGetUniformLocation(_currentShader.program, "uUseTexture"), 0);
				}
				
				// 启用混合
				glEnable(GL_BLEND);
				glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
				
				// 执行绘制
				glDrawElements(GL_TRIANGLES, _indices.length, GL_UNSIGNED_INT, 0);
				
				// 禁用混合
				glDisable(GL_BLEND);
				
				// 解绑资源
				glBindTexture(GL_TEXTURE_2D, 0);
				glBindVertexArray(0);
			}
			
			// 更新统计信息
			_batchCount++;
			_drawCalls++;
			_verticesRendered += _currentBatchSize * VERTICES_PER_QUAD;
			
			// 重置批量状态
			_currentBatchSize = 0;
			_currentTexture = 0;
			_vertices.length = 0;
			_indices.length = 0;
		}
		
		/**
		 * 结束批量渲染
		 */
		public function end():void
		{
			// 刷新剩余的批量
			flush();
			_currentShader = null;
		}
		
		/**
		 * 将Vector.<Number>转换为ByteArray
		 * @param vector 数值向量
		 * @return 字节数组
		 */
		private function vectorToByteArray(vector:Vector.<Number>):ByteArray
		{
			var byteArray:ByteArray = new ByteArray();
			byteArray.endian = Endian.LITTLE_ENDIAN;
			
			for each (var value:Number in vector)
			{
				byteArray.writeFloat(value);
			}
			
			return byteArray;
		}
		
		/**
		 * 将Vector.<uint>转换为ByteArray
		 * @param vector 无符号整数向量
		 * @return 字节数组
		 */
		private function vectorToByteArrayUint(vector:Vector.<uint>):ByteArray
		{
			var byteArray:ByteArray = new ByteArray();
			byteArray.endian = Endian.LITTLE_ENDIAN;
			
			for each (var value:uint in vector)
			{
				byteArray.writeUnsignedInt(value);
			}
			
			return byteArray;
		}
		
		/**
		 * 获取渲染统计信息
		 * @return 包含统计信息的对象
		 */
		public function getStats():Object
		{
			return {
				batchCount: _batchCount,
				drawCalls: _drawCalls,
				verticesRendered: _verticesRendered,
				currentBatchSize: _currentBatchSize,
				maxBatchSize: _maxBatchSize
			};
		}
		
		/**
		 * 重置统计信息
		 */
		public function resetStats():void
		{
			_batchCount = 0;
			_drawCalls = 0;
			_verticesRendered = 0;
		}
		
		/**
		 * 设置最大批量大小
		 * @param size 最大批量大小
		 */
		public function setMaxBatchSize(size:int):void
		{
			_maxBatchSize = size;
		}
		
		/**
		 * 释放资源
		 */
		public function dispose():void
		{
			with (Gl)
			{
				if (_batchVAO > 0)
				{
					glDeleteVertexArrays(1, _batchVAO);
					_batchVAO = 0;
				}
				
				if (_batchVBO > 0)
				{
					glDeleteBuffers(1, _batchVBO);
					_batchVBO = 0;
				}
				
				if (_batchEBO > 0)
				{
					glDeleteBuffers(1, _batchEBO);
					_batchEBO = 0;
				}
			}
			
			_vertices = null;
			_indices = null;
			_textures = null;
			_colors = null;
		}
	}
}