package ui.utils
{
	import agl.shader.Shader;
	import flash.utils.Dictionary;
	import com.vsdevelop.air.extension.glfw.Gl;

	/**
	 * 着色器缓存管理器
	 * 提供着色器程序的缓存和重用功能，避免重复编译相同的着色器
	 * @author Generated by AI Assistant
	 */
	public class ShaderCache
	{
		// 单例实例
		private static var _instance:ShaderCache;
		
		// 着色器缓存映射 (key: 着色器标识, value: Shader)
		private var _shaderCache:Dictionary;
		
		// 缓存统计
		private var _cacheHits:int = 0;
		private var _cacheMisses:int = 0;
		
		// 最大缓存数量
		private var _maxCacheSize:int = 50;
		
		/**
		 * 构造函数 (私有)
		 */
		public function ShaderCache()
		{
			if (_instance)
			{
				throw new Error("ShaderCache is a singleton class. Use getInstance() instead.");
			}
			
			_shaderCache = new Dictionary();
		}
		
		/**
		 * 获取单例实例
		 * @return ShaderCache实例
		 */
		public static function getInstance():ShaderCache
		{
			if (!_instance)
			{
				_instance = new ShaderCache();
			}
			return _instance;
		}
		
		/**
		 * 获取或创建着色器程序
		 * @param vertexShaderSource 顶点着色器源码
		 * @param fragmentShaderSource 片段着色器源码
		 * @return Shader实例
		 */
		public function getShader(vertexShaderSource:String, fragmentShaderSource:String):Shader
		{
			// 生成缓存键
			var key:String = generateShaderKey(vertexShaderSource, fragmentShaderSource);
			
			// 检查缓存中是否已存在
			var shader:Shader = _shaderCache[key] as Shader;
			if (shader)
			{
				_cacheHits++;
				return shader;
			}
			
			// 缓存未命中，创建新着色器
			_cacheMisses++;
			
			try
			{
				shader = new Shader(vertexShaderSource, fragmentShaderSource);
				
				// 验证着色器编译和链接是否成功
				if (!validateShader(shader))
				{
					throw new Error("Shader compilation or linking failed");
				}
				
				// 添加到缓存
				_shaderCache[key] = shader;
				
				// 检查缓存大小限制
				checkCacheSize();
				
				return shader;
			}
			catch (error:Error)
			{
				trace("Error creating shader: " + error.message);
				return null;
			}
		}
		
		/**
		 * 生成着色器缓存键
		 * @param vertexSource 顶点着色器源码
		 * @param fragmentSource 片段着色器源码
		 * @return 缓存键
		 */
		private function generateShaderKey(vertexSource:String, fragmentSource:String):String
		{
			// 使用简单的哈希算法生成键
			var hash:uint = 0;
			var combined:String = vertexSource + fragmentSource;
			
			for (var i:int = 0; i < combined.length; i++)
			{
				hash = ((hash << 5) - hash) + combined.charCodeAt(i);
				hash = hash & hash; // 转换为32位整数
			}
			
			return "shader_" + hash.toString(16);
		}
		
		/**
		 * 验证着色器是否编译和链接成功
		 * @param shader 着色器实例
		 * @return 是否成功
		 */
		private function validateShader(shader:Shader):Boolean
		{
			if (!shader || !shader.program)
			{
				return false;
			}
			
			try
			{
				with (Gl)
				{
					// 检查程序链接状态
					var linkStatus:int = glGetProgramiv(shader.program, GL_LINK_STATUS);
					if (linkStatus == GL_FALSE)
					{
						// 获取链接错误信息
						var infoLog:String = glGetProgramInfoLog(shader.program, 512);
						trace("Shader program linking failed: " + infoLog);
						return false;
					}
				}
				
				return true;
			}
			catch (error:Error)
			{
				trace("Error validating shader: " + error.message);
				return false;
			}
		}
		
		/**
		 * 检查缓存大小并清理旧着色器
		 */
		private function checkCacheSize():void
		{
			var cacheCount:int = 0;
			for (var key:String in _shaderCache)
			{
				cacheCount++;
			}
			
			if (cacheCount > _maxCacheSize)
			{
				// 简单的FIFO策略，删除第一个找到的着色器
				for (var cacheKey:String in _shaderCache)
				{
					var shader:Shader = _shaderCache[cacheKey] as Shader;
					if (shader && shader.program)
					{
						Gl.glDeleteProgram(shader.program);
					}
					delete _shaderCache[cacheKey];
					break;
				}
			}
		}
		
		/**
		 * 预加载常用着色器
		 * @param shaderConfigs 着色器配置数组
		 */
		public function preloadShaders(shaderConfigs:Array):void
		{
			for each (var config:Object in shaderConfigs)
			{
				if (config.vertexSource && config.fragmentSource)
				{
					getShader(config.vertexSource, config.fragmentSource);
				}
			}
		}
		
		/**
		 * 清理所有缓存的着色器
		 */
		public function clearCache():void
		{
			for (var key:String in _shaderCache)
			{
				var shader:Shader = _shaderCache[key] as Shader;
				if (shader && shader.program)
				{
					Gl.glDeleteProgram(shader.program);
				}
				delete _shaderCache[key];
			}
		}
		
		/**
		 * 获取缓存统计信息
		 * @return 包含统计信息的对象
		 */
		public function getStats():Object
		{
			var cacheCount:int = 0;
			for (var key:String in _shaderCache)
			{
				cacheCount++;
			}
			
			return {
				cacheHits: _cacheHits,
				cacheMisses: _cacheMisses,
				hitRate: _cacheHits / (_cacheHits + _cacheMisses),
				cachedShaders: cacheCount
			};
		}
		
		/**
		 * 设置最大缓存大小
		 * @param size 最大缓存数量
		 */
		public function setMaxCacheSize(size:int):void
		{
			_maxCacheSize = size;
			checkCacheSize();
		}
		
		/**
		 * 重新加载着色器 (用于开发时的热重载)
		 * @param vertexShaderSource 顶点着色器源码
		 * @param fragmentShaderSource 片段着色器源码
		 * @return 新的Shader实例
		 */
		public function reloadShader(vertexShaderSource:String, fragmentShaderSource:String):Shader
		{
			var key:String = generateShaderKey(vertexShaderSource, fragmentShaderSource);
			
			// 删除旧的着色器
			var oldShader:Shader = _shaderCache[key] as Shader;
			if (oldShader && oldShader.program)
			{
				Gl.glDeleteProgram(oldShader.program);
			}
			delete _shaderCache[key];
			
			// 创建新的着色器
			return getShader(vertexShaderSource, fragmentShaderSource);
		}
	}
}