package ui.utils
{
	import com.vsdevelop.air.extension.glfw.Gl;
	import flash.display.BitmapData;
	import flash.utils.Dictionary;
	import flash.utils.ByteArray;
	import flash.utils.Endian;

	/**
	 * 纹理缓存管理器
	 * 提供纹理的缓存、重用和统一管理功能，减少OpenGL纹理创建和销毁的开销
	 * @author Generated by AI Assistant
	 */
	public class TextureCache
	{
		// 单例实例
		private static var _instance:TextureCache;
		
		// 纹理缓存映射 (key: 纹理标识, value: TextureCacheEntry)
		private var _textureCache:Dictionary;
		
		// 未使用的纹理池 (按尺寸分组)
		private var _unusedTextures:Dictionary;
		
		// 缓存统计
		private var _cacheHits:int = 0;
		private var _cacheMisses:int = 0;
		private var _totalTextures:int = 0;
		
		// 最大缓存数量
		private var _maxCacheSize:int = 100;
		
		/**
		 * 构造函数 (私有)
		 */
		public function TextureCache()
		{
			if (_instance)
			{
				throw new Error("TextureCache is a singleton class. Use getInstance() instead.");
			}
			
			_textureCache = new Dictionary();
			_unusedTextures = new Dictionary();
		}
		
		/**
		 * 获取单例实例
		 * @return TextureCache实例
		 */
		public static function getInstance():TextureCache
		{
			if (!_instance)
			{
				_instance = new TextureCache();
			}
			return _instance;
		}
		
		/**
		 * 获取或创建纹理
		 * @param key 纹理唯一标识
		 * @param bitmapData 位图数据
		 * @param smooth 是否平滑处理
		 * @return OpenGL纹理ID
		 */
		public function getTexture(key:String, bitmapData:BitmapData, smooth:Boolean = true):uint
		{
			// 检查缓存中是否已存在
			var entry:TextureCacheEntry = _textureCache[key] as TextureCacheEntry;
			if (entry)
			{
				entry.lastUsed = new Date().time;
				entry.useCount++;
				_cacheHits++;
				return entry.textureId;
			}
			
			// 缓存未命中，创建新纹理
			_cacheMisses++;
			
			// 尝试从未使用的纹理池中获取
			var textureId:uint = getUnusedTexture(bitmapData.width, bitmapData.height);
			if (textureId == 0)
			{
				// 创建新纹理
				textureId = createNewTexture();
				_totalTextures++;
			}
			
			// 上传纹理数据
			uploadTextureData(textureId, bitmapData, smooth);
			
			// 添加到缓存
			entry = new TextureCacheEntry();
			entry.textureId = textureId;
			entry.width = bitmapData.width;
			entry.height = bitmapData.height;
			entry.smooth = smooth;
			entry.lastUsed = new Date().time;
			entry.useCount = 1;
			
			_textureCache[key] = entry;
			
			// 检查缓存大小限制
			checkCacheSize();
			
			return textureId;
		}
		
		/**
		 * 释放纹理到未使用池
		 * @param key 纹理标识
		 */
		public function releaseTexture(key:String):void
		{
			var entry:TextureCacheEntry = _textureCache[key] as TextureCacheEntry;
			if (entry)
			{
				// 移动到未使用池
				var sizeKey:String = entry.width + "x" + entry.height;
				if (!_unusedTextures[sizeKey])
				{
					_unusedTextures[sizeKey] = new Vector.<uint>();
				}
				(_unusedTextures[sizeKey] as Vector.<uint>).push(entry.textureId);
				
				// 从缓存中移除
				delete _textureCache[key];
			}
		}
		
		/**
		 * 从未使用池获取纹理
		 * @param width 纹理宽度
		 * @param height 纹理高度
		 * @return 纹理ID，如果没有可用纹理返回0
		 */
		private function getUnusedTexture(width:int, height:int):uint
		{
			var sizeKey:String = width + "x" + height;
			var textures:Vector.<uint> = _unusedTextures[sizeKey] as Vector.<uint>;
			
			if (textures && textures.length > 0)
			{
				return textures.pop();
			}
			
			return 0;
		}
		
		/**
		 * 创建新的OpenGL纹理
		 * @return 纹理ID
		 */
		private function createNewTexture():uint
		{
			return Gl.glGenTextures(1);
		}
		
		/**
		 * 上传纹理数据到OpenGL
		 * @param textureId 纹理ID
		 * @param bitmapData 位图数据
		 * @param smooth 是否平滑处理
		 */
		private function uploadTextureData(textureId:uint, bitmapData:BitmapData, smooth:Boolean):void
		{
			with (Gl)
			{
				// 绑定纹理
				glBindTexture(GL_TEXTURE_2D, textureId);
				
				// 设置纹理参数
				if (smooth)
				{
					glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
					glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
				}
				else
				{
					glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
					glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
				}
				
				glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
				glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
				
				// 转换位图数据为字节数组
				var pixels:ByteArray = new ByteArray();
				pixels.endian = Endian.LITTLE_ENDIAN;
				
				for (var y:int = 0; y < bitmapData.height; y++)
				{
					for (var x:int = 0; x < bitmapData.width; x++)
					{
						var pixel:uint = bitmapData.getPixel32(x, y);
						pixels.writeByte((pixel >> 16) & 0xFF); // R
						pixels.writeByte((pixel >> 8) & 0xFF);  // G
						pixels.writeByte(pixel & 0xFF);         // B
						pixels.writeByte((pixel >> 24) & 0xFF); // A
					}
				}
				
				// 上传纹理数据
				glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, bitmapData.width, bitmapData.height, 0, GL_RGBA, GL_UNSIGNED_BYTE, pixels);
				
				// 解绑纹理
				glBindTexture(GL_TEXTURE_2D, 0);
			}
		}
		
		/**
		 * 检查缓存大小并清理旧纹理
		 */
		private function checkCacheSize():void
		{
			var cacheCount:int = 0;
			for (var key:String in _textureCache)
			{
				cacheCount++;
			}
			
			if (cacheCount > _maxCacheSize)
			{
				// 找到最久未使用的纹理并释放
				var oldestKey:String = null;
				var oldestTime:Number = Number.MAX_VALUE;
				
				for (var cacheKey:String in _textureCache)
				{
					var entry:TextureCacheEntry = _textureCache[cacheKey] as TextureCacheEntry;
					if (entry.lastUsed < oldestTime)
					{
						oldestTime = entry.lastUsed;
						oldestKey = cacheKey;
					}
				}
				
				if (oldestKey)
				{
					releaseTexture(oldestKey);
				}
			}
		}
		
		/**
		 * 清理所有缓存
		 */
		public function clearCache():void
		{
			// 删除所有缓存的纹理
			for (var key:String in _textureCache)
			{
				var entry:TextureCacheEntry = _textureCache[key] as TextureCacheEntry;
				Gl.glDeleteTextures(1, entry.textureId);
				delete _textureCache[key];
			}
			
			// 删除所有未使用的纹理
			for (var sizeKey:String in _unusedTextures)
			{
				var textures:Vector.<uint> = _unusedTextures[sizeKey] as Vector.<uint>;
				for each (var textureId:uint in textures)
				{
					Gl.glDeleteTextures(1, textureId);
				}
				delete _unusedTextures[sizeKey];
			}
			
			_totalTextures = 0;
		}
		
		/**
		 * 获取缓存统计信息
		 * @return 包含统计信息的对象
		 */
		public function getStats():Object
		{
			var cacheCount:int = 0;
			var unusedCount:int = 0;
			
			for (var key:String in _textureCache)
			{
				cacheCount++;
			}
			
			for (var sizeKey:String in _unusedTextures)
			{
				var textures:Vector.<uint> = _unusedTextures[sizeKey] as Vector.<uint>;
				unusedCount += textures.length;
			}
			
			return {
				cacheHits: _cacheHits,
				cacheMisses: _cacheMisses,
				hitRate: _cacheHits / (_cacheHits + _cacheMisses),
				cachedTextures: cacheCount,
				unusedTextures: unusedCount,
				totalTextures: _totalTextures
			};
		}
		
		/**
		 * 设置最大缓存大小
		 * @param size 最大缓存数量
		 */
		public function setMaxCacheSize(size:int):void
		{
			_maxCacheSize = size;
			checkCacheSize();
		}
	}
}

/**
 * 纹理缓存条目类
 * 存储纹理的元数据和使用统计
 */
class TextureCacheEntry
{
	public var textureId:uint;
	public var width:int;
	public var height:int;
	public var smooth:Boolean;
	public var lastUsed:Number;
	public var useCount:int;
}