package ui.containers
{
	import ui.core.UIComponent;
	import ui.layout.LayoutManager;
	import flash.geom.Rectangle;

	/**
	 * 容器组件类
	 * 支持布局管理器的容器，可以自动排列子组件
	 * @author Generated by AI Assistant
	 */
	public class Container extends UIComponent
	{
		// 布局管理器
		protected var _layoutManager:LayoutManager;
		
		// 是否自动布局
		protected var _autoLayout:Boolean = true;
		
		// 布局属性
		public var borderRegion:String; // BorderLayout使用的区域属性
		
		
		public var layoutWeight:Number = 0;
		// 布局约束属性
		public var gridPosition:Object; // GridLayout使用的网格位置 {row: int, col: int, rowSpan: int, colSpan: int}
		/**
		 * 构造函数
		 * @param x X坐标
		 * @param y Y坐标
		 * @param width 宽度
		 * @param height 高度
		 */
		public function Container(x:Number = 0, y:Number = 0, width:Number = 100, height:Number = 100)
		{
			super(x, y, width, height);
		}
		
		/**
		 * 设置布局管理器
		 * @param layoutManager 布局管理器实例
		 */
		public function setLayoutManager(layoutManager:LayoutManager):void
		{
			if (_layoutManager != null)
			{
				_layoutManager.dispose();
			}
			
			_layoutManager = layoutManager;
			
			// 如果启用自动布局，立即执行布局
			if (_autoLayout && _layoutManager != null)
			{
				updateLayout();
			}
		}
		
		/**
		 * 获取布局管理器
		 * @return 当前的布局管理器
		 */
		public function getLayoutManager():LayoutManager
		{
			return _layoutManager;
		}
		
		/**
		 * 添加子组件（重写父类方法以支持布局）
		 * @param child 要添加的子组件
		 * @return 添加的子组件
		 */
		public override function addChild(child:UIComponent):UIComponent
		{
			return addChildWithConstraints(child, null);
		}
		
		/**
		 * 添加子组件并指定布局约束
		 * @param child 要添加的子组件
		 * @param constraints 布局约束参数，传递给布局管理器
		 * @return 添加的子组件
		 */
		public function addChildWithConstraints(child:UIComponent, constraints:Object):UIComponent
		{
			var result:UIComponent = super.addChild(child);
			
			// 如果有布局管理器，将组件添加到布局管理器
			if (_layoutManager != null)
			{
				_layoutManager.addComponent(child, constraints);
			}
			
			// 如果启用自动布局，重新布局
			if (_autoLayout && _layoutManager != null)
			{
				updateLayout();
			}
			
			return result;
		}
		
		/**
		 * 移除子组件（重写父类方法以支持布局）
		 * @param child 要移除的子组件
		 * @return 移除的子组件
		 */
		public override function removeChild(child:UIComponent):UIComponent
		{
			var result:UIComponent = super.removeChild(child);
			
			// 如果启用自动布局，重新布局
			if (_autoLayout && _layoutManager != null)
			{
				updateLayout();
			}
			
			return result;
		}
		
		/**
		 * 根据索引移除子组件（重写父类方法以支持布局）
		 * @param index 子组件索引
		 * @return 移除的子组件
		 */
		public override function removeChildAt(index:int):UIComponent
		{
			var result:UIComponent = super.removeChildAt(index);
			
			// 如果启用自动布局，重新布局
			if (_autoLayout && _layoutManager != null)
			{
				updateLayout();
			}
			
			return result;
		}
		
		/**
		 * 更新布局
		 * 使用当前的布局管理器重新排列子组件
		 */
		public function updateLayout():void
		{
			if (_layoutManager != null && _layoutManager.enabled)
			{
				_layoutManager.layout(this);
			}
		}
		
		/**
		 * 标记布局需要更新
		 * 在下一次渲染时会自动调用updateLayout
		 */
		public function invalidateLayout():void
		{
			if (_autoLayout && _layoutManager != null)
			{
				updateLayout();
			}
		}
		
		/**
		 * 获取首选尺寸
		 * 根据布局管理器计算容器的首选尺寸
		 * @return 首选尺寸矩形
		 */
		public function getPreferredSize():Rectangle
		{
			if (_layoutManager != null)
			{
				return _layoutManager.getPreferredSize(this);
			}
			
			// 如果没有布局管理器，返回当前尺寸
			return new Rectangle(0, 0, _width, _height);
		}
		
		/**
		 * 设置容器尺寸（重写父类方法以支持布局）
		 * @param value 新的宽度
		 */
		public override function set width(value:Number):void
		{
			if (_width != value)
			{
				super.width = value;
				
				// 如果启用自动布局，重新布局
				if (_autoLayout && _layoutManager != null)
				{
					updateLayout();
				}
			}
		}
		
		/**
		 * 设置容器尺寸（重写父类方法以支持布局）
		 * @param value 新的高度
		 */
		public override function set height(value:Number):void
		{
			if (_height != value)
			{
				super.height = value;
				
				// 如果启用自动布局，重新布局
				if (_autoLayout && _layoutManager != null)
				{
					updateLayout();
				}
			}
		}
		
		/**
		 * 设置是否启用自动布局
		 * @param value 是否启用自动布局
		 */
		public function set autoLayout(value:Boolean):void
		{
			_autoLayout = value;
			
			// 如果启用自动布局，立即执行布局
			if (_autoLayout && _layoutManager != null)
			{
				updateLayout();
			}
		}
		
		/**
		 * 获取是否启用自动布局
		 * @return 是否启用自动布局
		 */
		public function get autoLayout():Boolean
		{
			return _autoLayout;
		}
		
		/**
		 * 渲染容器及其子组件
		 */
		public override function render():void
		{
			// 先渲染容器本身
			super.render();
			
			// 然后渲染所有子组件
			for (var i:int = 0; i < _children.length; i++)
			{
				if (_children[i].visible)
				{
					_children[i].render();
				}
			}
		}
		
		/**
		 * 检查点击测试（重写父类方法以支持子组件）
		 * @param pointX X坐标
		 * @param pointY Y坐标
		 * @return 是否在组件内
		 */
		public override function hitTest(pointX:Number, pointY:Number):Boolean
		{
			// 首先检查是否在容器范围内
			if (!super.hitTest(pointX, pointY))
			{
				return false;
			}
			
			// 检查是否点击了子组件
			for (var i:int = _children.length - 1; i >= 0; i--)
			{
				var child:UIComponent = _children[i];
				if (child.visible && child.enabled && child.hitTest(pointX, pointY))
				{
					return true;
				}
			}
			
			// 如果没有子组件被点击，返回容器本身的点击测试结果
			return true;
		}
		
		/**
		 * 释放资源（重写父类方法）
		 */
		public override function dispose():void
		{
			// 释放布局管理器
			if (_layoutManager != null)
			{
				_layoutManager.dispose();
				_layoutManager = null;
			}
			
			// 调用父类的释放方法
			super.dispose();
		}
	}
}